### ISSUE TITLE
light==yellow

### ISSUE THREAD

**Issue by tofr** [RohanAhammed/RoMoSo#1]
database, you say? more details...

how exactly are you storing the station info --- so as to lend to a depth-first probing?

**Comment by cmohri** [comment]
We're currently looking for a comprehensive csv file with information that we think will be useful. We've found workable csv files. We'll be storing each station within a class called Station, which will have a number of variables that come from a csv file. Each StationLine will essentially be a doubly-linked list of Stations, and we will grow the number of StationLines within our Map as we establish the basics.
